### ISSUE TITLE
use more map-levels

### ISSUE THREAD

**Issue by osmvermesser** [ChristopherGittner/OSMBugs#10]
to make better notes (position definiton) it would be better to use more map-levels.

german: es wäre wünschenswert, wenn die Karte weiter aufgezoomt werden könnte um Notes präziser platzieren zu können. Immerhin ist es eine Touchpad-App.

Jan alias Lübeck

**Comment by ChristopherGittner** [comment]
Hi Jan,

have you tried the current Version (0-9-6)?
There the zoom level has been increased by 3 steps.

Let me know, if this is good enough for your purpose.

**Comment by ChristopherGittner** [comment]
Duplicate of #7

**Comment by osmvermesser** [comment]
Hi Christopher,current update - now is ok!thanks and regards JanChristopher Gittner <notifications@github.com> hat am 21. August 2017 um 17:31 geschrieben:Hi Jan,have you tried the current Version (0-9-6)? There the zoom level has been increased by 3 steps.Let me know, if this is good enough for your purpose.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread. Mit freundlichen GrüßenJan Tappenbeck-----------------------------------OpenStreetMap (OSM) - das FREIE Kartenprojekthttp://www.openstreetmap.deTREFFPUNKTE einfach weitergeben mit OpenStreetMap.Einzelheiten hierzu finden Sie auf meinem Blog unter ...http://blog.tappenbeck.net/2013/11/26/openstreetmap-treffpunkte-einfach-weitergeben/OpenStreetMap mit (FEHLER)HINWEISEN unterstützenEinzelheiten hierzu finden Sie auf meinem Blog unter ...http://blog.tappenbeck.net/2013/12/13/openstreetmap-mit-wenigen-schritten-das-projekt-unterstuetzen/... dann gibt es da noch die Modellbahn Spur Z - meine Link-Tipps finden sich unterhttp://blog.tappenbeck.net/2015/02/19/linkliste-modellbahn-spur-z-co/
