### ISSUE TITLE
Bugs persistence

### ISSUE THREAD

**Issue by eehpcm** [ChristopherGittner/OSMBugs#13]
This may be related to https://github.com/ChristopherGittner/OSMBugs/issues/12 or it may be completely different.

Many bugs never go away.  I fix an error.  The map tile doesn't change (see https://github.com/ChristopherGittner/OSMBugs/issues/12) but in most (all?) cases the bug doesn't go away either.  New bugs I introduce (oops!) appear, but ones I fix hang around.

In some cases maybe my fix was wrong in some way, but I fixed a feature (a footpath passing through a car park that actually terminated at the boundary of the car park and followed a different route anyway) and the bug is still there.  I deleted the existing footpath (which was wrong in so many ways) and added a new footpath.  That's an Osmose bug.  There are other Osmose bugs that are hanging around.

I replaced a URL that Keepright picked up as not containing the name of the location in the web page (it didn't, because the URL was to a site that no longer has content).  Keepright still shows the same bug, relating to the same empty web site.  Etc.

Mapdust has no bugs shown at all.

I'm not sure if OSM notes is keeping up or not.  I didn't really pay attention to it.

They're all enabled in settings.  I've tried settings->keepright->reset visible bugs.  Doesn't seem to do anything.   Similarly android's settings->apps->osmbugs->flush cached data.

The ones I've mentioned are at least a week old.  Do these bug monitors really update so infrequently?  If so, some help information in the app mentioning this would be useful.

**Comment by ChristopherGittner** [comment]
Hi eehpcm,

The Bugs not vanishing immediately, as soon as you fix them might be that Keepright and Osmose run the checks for new/existing Bugs on a certain time interval (Maybe once a week), as you already guessed :-)
That would mean that, even if you go over to the platforms Homepage, your bugs will still be there, until the next update cycle. If this is not the case, please comment again on this Issue!

Btw. Mapdust and OSM Notes should vanish, immediately, after you close the Bug either through the App or the platforms homepage.

**Comment by eehpcm** [comment]
So far I've not explicitly closed bugs but waited for Mapdust or whatever to notice.

After all, I might think I've fixed a bug but haven't.  It seemed better to let Mapdust or whatever figure out that the bug really has vanished.  As some have, since I first brought up the issue.
