### ISSUE TITLE
feedback in app goes to broken email address

### ISSUE THREAD

**Issue by matkoniecz** [ChristopherGittner/OSMBugs#14]
The recipient server did not accept our requests to connect. Learn more at https://support.google.com/mail/answer/7720 [mail.gittner.org. 91.1.129.239: generic::failed_precondition: connect error (0): error]

Final-Recipient: rfc822; christopher@gittner.org
Action: delayed
Status: 4.4.1
Diagnostic-Code: smtp; The recipient server did not accept our requests to connect. Learn more at https://support.google.com/mail/answer/7720
 [mail.gittner.org. 91.1.129.239: generic::failed_precondition: connect error (0): error]
Last-Attempt-Date: Fri, 13 Oct 2017 00:10:53 -0700 (PDT)
Will-Retry-Until: Sat, 14 Oct 2017 23:20:17 -0700 (PDT)

**Comment by matkoniecz** [comment]
Note to self: after fix update app rating

**Comment by ChristopherGittner** [comment]
Mail Server was down.
Should be fixed now...
