### ISSUE TITLE
Can't load Mapnik tiles anymore

### ISSUE THREAD

**Issue by laurentriffard** [ChristopherGittner/OSMBugs#18]
Hi,
since a few days, Osmbugs can't download Mapnik tiles as a background map. Other map styles (opentopo, transport map) work as usual.

This seems to be related to osmdroid library, using a fixed user-agent, and being blocked by Mapnick tile server. See https://github.com/osmdroid/osmdroid/issues/1289

Please, can you ugrade to osmdroid v0.6.1 and publish new apk on F-Droid ?
Thanks.

**Comment by ChristopherGittner** [comment]
Hi,

Thank you very much for the Issue, and the Hint how to fix this.
I really appreciate it!

A new version has been uploaded and will hopefully be build by F-Droid soon.

**Comment by laurentriffard** [comment]
Hi, 
Just got Osmbugs v1-1-5 from F-Droid : Mapnik tiles are now downloaded just fine.
Thank you for the quick fix.
