### ISSUE TITLE
App crashes when using the Zoom Buttons

### ISSUE THREAD

**Issue by ChristopherGittner** [ChristopherGittner/OSMBugs#20]
Figure out what causes this.

**Comment by Mannivu** [comment]
I don't have this issue using Android 9 (MIUI Global 10.3) on Xiaomi MI8

**Comment by ChristopherGittner** [comment]
Seems to be this Issue in Osmdroid.

https://github.com/osmdroid/osmdroid/issues/1299

Wait for a new release which will hopefully patch this...

**Comment by InI4** [comment]
Currently I use a fork of 6.1.0 with the patch described there by @shorti1996 .
I did not understand, why they reverted otherwise good code. Anxiously waiting for 6.1.1 with that patch and without the revert and all the other goodies. Sigh.

**Comment by ChristopherGittner** [comment]
There has been a fix published over at Osmdroid. So now we wait for 6.1.1...
