### ISSUE TITLE
Adding note from the menu does not display dialogue until map moves

### ISSUE THREAD

**Issue by lightonflux** [ChristopherGittner/OSMBugs#21]
Version 1-2-0 from F-Droid. Also tested the same version from gplay.

When using the menu to add a note, nothing happens.

The dialogue only appears when after the map is moved.

![bug](https://user-images.githubusercontent.com/1377943/60038044-7e130980-96b3-11e9-8195-8adbd4e3286c.gif)

**Comment by ChristopherGittner** [comment]
Hi lightonflux,

to add a Bug you select add Bug from the Menu, and then click anywhere on the map, where to add the Bug.
I see, that this process is not clear to the user at first glance, so i added a message telling the user what to do :-)

**Comment by lightonflux** [comment]
Thanks.

**Comment by lightonflux** [comment]
Thanks for the fix.

I just tested it with someone and here the feedback:

 * first time the person did not notice the notification bubble at the bottom of the screen
 * then when trying the feature several times it did not appear every time, looks like a timing issue

Some suggestions: 

 * add a floating + button
 * make it possible to move the map after the button was pressed

Some inspiration from StreetComplete

![t](https://user-images.githubusercontent.com/1377943/60773746-107ec880-a10a-11e9-9cf8-9e98dd0a9e91.gif)

**Comment by ChristopherGittner** [comment]
Ok, you are right. The current implementation is not very user-friendly. Tapping the Button a second time disables the "Add Note on Map Click" feature. But you can only see that if you see the Bug symbol turning Red or Gray on the Menu Bar.

I really like the Way it is implemented in StreetComplete. I will try to do it like they do.

**Comment by ChristopherGittner** [comment]
With Version 1-3-0 i have now implemented such a Feature... Finally :-D
