### ISSUE TITLE
A confusing icon on OSMBugs's UI

### ISSUE THREAD

**Issue by b450mhdv** [ChristopherGittner/OSMBugs#27]
@ChristopherGittner 

Hello, I found a problem with the app's UI design. When I first used this app, I was curious about the "checkbox" icon in the menu. Although the checkbox in the menu can enable and disable GPS, this design is different from the common design I saw in other popular apps. Besides, when I enable the GPS and open the menu again, the checkbox disappear, which will make users confusing. As a suggestion, if you can use a more intuitive design for this, it may greatly improve the user experience. Could you fix this issue?
![OsmBugs-github](https://user-images.githubusercontent.com/78015408/113532142-3ac22a80-95fd-11eb-8c5c-58b9d89bf92d.png)
![OsmBugs-github2](https://user-images.githubusercontent.com/78015408/113532150-3e55b180-95fd-11eb-97f3-1dcd6d6283e9.png)

**Comment by ChristopherGittner** [comment]
Hi @b450mhdv ,

thanks for reporting this issue, which i did not seem to note myself...

The current Version of OSMBugs does no longer include the Enable/Disable GPS functionality. If you really need this function, feel free to comment on this issue again :-)
