### ISSUE TITLE
Failed to download Errors

### ISSUE THREAD

**Issue by ivanbranco** [ChristopherGittner/OSMBugs#32]
Every time I try to download errors I get the following error:
`Failed to download Errors: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject`

I have version 1-3-6

**Comment by opk12** [comment]
Is this the MapDust failure from #31?

**Comment by mnalis** [comment]
latest OSMBugs 1.4.0 does not have Mapdust anymore (as the service has been terminated), and I cannot reproduce this error. Can you close it @ivanbranco if it no longer happens for you either?

**Comment by ivanbranco** [comment]
Dunno, since I updated the f-droid version, it keept crashing at start. Tried uninstalling, installing again, restarting phone ecc. but it kept crashing. I had to download the Google Play Store version

**Comment by mnalis** [comment]
Interesting @ivanbranco, I've seen few crashes with f-droid's 1.4.0 (on Android 14), but none that survive reinstall. Although, if you also have Google Play, it might be trying to reinstall the data  from the cloud. I've seen that happen before, and manually doing `clear data` after reinstall fixed the situation. Maybe it can help your case too.

If not, it would be useful if you could report the crash log and android version...

**Comment by opk12** [comment]
Some crashes have been fixed since 1.4.0 has been released, so it may be worth trying the next version. When it comes to  crash reporting, I love [LogFox](https://github.com/F0x1d/LogFox), I launch it and it opens a notification for each crash that happened, then I tap the `Copy` button in the notification, and paste into GitHub.

**Comment by opk12** [comment]
Side note if anyone cannot update for whatever reason: 1.3.6 can be installed manually,
- from f-droid.org, click [here](https://f-droid.org/en/packages/org.gittner.osmbugs/), scroll to the bottom `Version 1-3-6` - `Download APK`
- in the future, the APK will be in [F-droid's archive](https://apt.izzysoft.de/fdroid/index/apk/org.gittner.osmbugs?repo=archive) (this izzysoft webpage is a graphical browser, but the download links point to the official f-droid.org server)
