### ISSUE TITLE
Switch to OAuth 2

### ISSUE THREAD

**Issue by danieldegroot2** [ChristopherGittner/OSMBugs#33]
Switch to OAuth 2 from HTTP Basic Auth and OAuth 1.0a. They are being deprecated.
See https://github.com/openstreetmap/operations/issues/867

**Comment by mnalis** [comment]
Note critical days from https://github.com/openstreetmap/operations/issues/867#issuecomment-191195405

> Repeating [the announcement](https://community.openstreetmap.org/t/oauth-1-0a-and-http-basic-auth-shutdown/108490),
> The Operations Working Group is shutting down OAuth 1.0a and HTTP Basic Auth in 2024. They have been deprecated since 2023 and their role in authorization has replaced by OAuth 2.0 which the standard authorization method for most systems. This change will have three key dates:
>  -  March 1st, 2024: New OAuth 1.0a application registrations are disabled. Existing applications will not be impacted. HTTP Basic Auth will not be impacted.
>  -  May 1st, 2024: Sysadmins will start brownouts to find applications that are still using OAuth 1.0a or HTTP Basic Auth
>  -  June 1st, 2024: OAuth 1.0a and HTTP Basic Auth will be shut down.

**Comment by mnalis** [comment]
@ChristopherGittner is OSMBugs app still being maintained? 

I see last commit was 3 years ago, and OpenStreetMap Notes support will break in few weeks (due to OAuth2 requrements) unless it receives a fix, which would be a shame...

If it is a lack of time but you are still active, would you accept someone else making a PR for Oauth2 support? Or some other solution?

**Comment by ChristopherGittner** [comment]
Hey there,

i really had too much other stuff to do in the Past so i were not able to keep OSMBugs up to date.

I'd like to create a patch for this issue but will not be able to make it in the next 2-3 Weeks.
I will get my hands onto this after that to prevent the break. And maybe also tackle some of the other issues still open here...

**Comment by mnalis** [comment]
Oauth2 seems to be working now in OSMBugs 1.4.0 :tada:

**Comment by danieldegroot2** [comment]
Completed in https://github.com/ChristopherGittner/OSMBugs/commit/853fc847a9bf162881c9f1f91c231065cf065b03 part of [`🏷️ 1-4-0`](https://github.com/ChristopherGittner/OSMBugs/releases/tag/1-4-0)
