### ISSUE TITLE
Use preferred tile.openstreetmap.org URL

### ISSUE THREAD

**Issue by mnalis** [ChristopherGittner/OSMBugs#34]
as noted in https://github.com/openstreetmap/operations/issues/737, `{a,b,c}.tile.openstreetmap.org` is deprecated, and one should simply use `https://tile.openstreetmap.org` - no subdomains, no short names.

Latest F-droid release (OsmBug 1.3.6) at least seems to use `a.tile.openstreetmap.org` and its friends.

**Comment by opk12** [comment]
Just a heads up that the network log for version 1.4.0 only uses `tile.openstreetmap.org` but I do not see related changes in the recent commits. Maybe something changed in OsmDroid?

**Comment by mnalis** [comment]
Yes, I can confirm it seems to be solved with 1.4.0 F-droid release too! Closing.
