### ISSUE TITLE
F-Droid Version not up to date

### ISSUE THREAD

**Issue by Mannivu** [ChristopherGittner/OSMBugs#36]
I see that the app has been updated nearly a month ago, and the GPlay version is up to date, but there's no update available for the F-Droid version.

**Comment by opk12** [comment]
Solved. 1.4.0 is now on F-droid.

**Comment by opk12** [comment]
In general, [this FAQ](https://f-droid.org/en/docs/FAQ_-_App_Developers/#ive-published-a-new-release-why-is-it-not-in-the-repository) applies - the long build queue is a known effect of F-droid not having a powerful enough build server. And they're constantly adding apps. For similar cases, I'd say
- Open the app page on f-droid.org ([example](https://f-droid.org/en/packages/org.gittner.osmbugs/)).
- Click `Build metadata`.
- Is `UpdateCheckMode: Tags`? (usually at the bottom)
- If not, then open an issue at [fdroiddata](https://gitlab.com/fdroid/fdroiddata), if there is not one already.
- If yes, then the app either is waiting to be built ([in this list](https://monitor.f-droid.org/builds/needsupdate)), or it has been built ([in this list](https://monitor.f-droid.org/builds/build)) and is waiting for the other apps (it will enter the repo when the build cycle completes).

**Comment by Mannivu** [comment]
Oh, I see. Thank you for your explanation.
