### ISSUE TITLE
send geo: intents on request (enhancement)

### ISSUE THREAD

**Issue by mnalis** [ChristopherGittner/OSMBugs#4]
it would be great if (when one opens some specific bug) there would be an option to send geo: intent with that bug location.

That would allow to combine OSMBugs with other apps (for example, with OSMAnd to navigate to the bug, or with Vespucci to fix osmose error etc)

**Comment by DJaeger** [comment]
Something like a "Navigate to"-Button

**Comment by mnalis** [comment]
yes, that would be great!
