### ISSUE TITLE
OSM Notes ignore user credentials

### ISSUE THREAD

**Issue by mnalis** [ChristopherGittner/OSMBugs#5]
It seems that creating new OSM Note always do it as anonymous, even when username/password for Notes is entered in preferences

(OSMBugs 0.9.1 from f-droid)

**Comment by DJaeger** [comment]
It will be created as anonymous and be solved with username.
See this test note:
http://www.openstreetmap.org/note/440977

**Comment by mnalis** [comment]
I can confirm username is applied on close, but not on create or comment. 

It would be great if it also worked on create/comment. (for example, I mostly quickly update or create notes in the field on mobile phone, and later on desktop use http://my-notes.osm-hr.org/ to find notes I worked on to fix them in JOSM - if they are marked as from anonymous, I can't find them)
