### ISSUE TITLE
allow more zoom

### ISSUE THREAD

**Issue by mnalis** [ChristopherGittner/OSMBugs#7]
sometimes, it would help to be able to zoom in more to see details of bugs, but "+" is disabled at some depth. Would it be possible to increase it by at least 1-2 zoom levels?

**Comment by ChristopherGittner** [comment]
I have increased the Zoom level by 3 levels. But keep in mind, that the default Tile Source does not load new Tiles at this Zoom level. You'll have to zoom out for the Tiles to start loading
