### ISSUE TITLE
posibility of persistant data for offline use?

### ISSUE THREAD

**Issue by mnalis** [ChristopherGittner/OSMBugs#8]
It would be good if downloaded bugs data was persistent (in the same way that background map seems to be).

Many of the times I'm in the area with bad or nonexistant cell signal, so I need offline functionality - that is, download bugs and background map of the area beforehand when I have data connectivity, and then go out to map non covered area.

OSMBugs does seem to work for a while, but after some nondeterministic time (few to dozens of minuts, usually after switching apps etc) all the bugs dissapear from display (while the background map stays visible ok).

it would be great if keepright/osmose/Notes could persist the same way the background map seems to.

**Comment by ChristopherGittner** [comment]
With Version 1-3 of OSMBugs the Bugs will be stored in a Database which is only reloaded when explicitly triggered through the reload Button. Meaning the Bugs will now still be available after App closing.

But... there is no sort of offline commenting functionality, as this will always require an active Network connection. This might be something someone can introduce in the Future.
